config/routes.rb
Rails.application.routes.draw do

  get 'shared/_navbarwelcome'

  resources :papers
  resources :papers

  get 'papers/index'

  get 'papers/new'

  get 'papers/show'

  get 'papers/edit'

  get 'site/cognitiva'

  get 'site/creditos'

  get 'site/credito'

  get 'site/links'

  get 'site/freeman'

  get 'site/kandel'

  get 'site/redolar'

  get 'docs/iacompu'

  get 'docs/antidepresivos'

  get 'docs/esclerosis'

  get 'site/psiquiatria'

  get 'docs/gage'

  get 'site/psicologia'

  get 'docs/secuencias'

  get 'site/bioinformatica'

  get 'docs/modelado'

  get 'site/computacional'

  get 'docs/dne'

  get 'docs/atencion'

  get 'docs/neurona'

  get 'site/cel'

  get 'docs/ionico'

  get 'site/mol'

  get 'site/about'

  get 'site/noticias'

  get 'dic/diccionario'

  get 'dic/z'

  get 'dic/y'

  get 'dic/x'

  get 'dic/w'

  get 'dic/v'

  get 'dic/u'

  get 'dic/t'

  get 'dic/s'

  get 'dic/r'

  get 'dic/q'

  get 'dic/p'

  get 'dic/o'

  get 'dic/n'

  get 'dic/m'

  get 'dic/l'

  get 'dic/k'

  get 'dic/j'

  get 'dic/i'

  get 'dic/h'

  get 'dic/g'

  get 'dic/f'

  get 'dic/e'

  get 'dic/d'

  get 'dic/c'

  get 'dic/b'

  get 'dic/a'

  get 'site/biblio'

  get 'site/ia'

  get 'site/psicofarma'

  get 'site/aplicada'

  get 'site/neuropsico'

  get 'site/neurologia'

  get 'site/comp'

  get 'site/anatomia'

  get 'site/cognitiva'

  get 'site/cognitiva'

  get 'site/celular'

  get 'shared/navbar'

  get 'shared/navbar'

  get 'welcome/index'

   root 'welcome#index'

end

app/models/contact.rb
#class Contact < MailForm::Base
#  attribute :nombre,      :validate => true
#  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
#  attribute :mensaje
#  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
 # def headers
 #   {
 #       :subject => "Contacto Lwdn",
 #       :to => "supersexador.de.pollos@gmail.com",
 #       :from => %("#{nombre}" <#{email}>)
 #   }
#  end
#end

app/models/lwdnc.rb
class Lwdnc < ActiveRecord::Base
end

app/models/paper.rb
class Paper < ActiveRecord::Base
end

app/models/papers_mol.rb
class PapersMol < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Gracias por contactar con nosotros. Te responderemos lo antes posible.'
    else
      flash.now[:error] = 'No se ha podido mandar el mensaje.'
      render :new
    end
  end
end

app/controllers/dic_controller.rb
class DicController < ApplicationController
  def a
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def ionico
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'El nuevo documento se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'El documento ha sido actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:id, :autores, :título, :año, :idioma, :descarga)
    end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def navbar
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dic_helper.rb
module DicHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/lwdncs_helper.rb
module LwdncsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/papers_mols_helper.rb
module PapersMolsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<br>
<br>
<br>

<div class="col-lg-6 col-lg-offset-3 well">
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<br>
<br>
<br>
<br>
<div align="center" class="col-lg-6 col-lg-offset-3 well">
  <h3>Formulario de contacto</h3>
  <div>És necesario rellenar todos los campos del formulario:</div>

  <br>
  <div style="wrap">
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <div style="jumbotron">
      <%= f.input :nombre, class: 'form-control', autofocus: true, placeholder: 'nombre' %>
      <%= f.input :email, :required => true %>
      <%= f.input :mensaje, :as => :text, :required => true %>
     </div>
  </div>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        </br>
        <%= f.button :submit, 'Envia el mensaje', :class=> "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/dic/d.html.erb
<html lang="es">
<nav>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</nav>
<br>
<br>
<body>
<div style="margin: 0px auto; text-align: center; width: 1150px;" >

  <a href="dic/diccionario"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/a.png" height="20" width="20" alt=""/></a>
  <a href="dic/b"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/b.png" height="20" width="20" alt=""/></a>
  <a href="dic/c"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/c.png" height="20" width="20" alt=""/></a>
  <a href="dic/d"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/d.png" height="20" width="20" alt=""/></a>
  <a href="dic/e"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/e.png" height="20" width="20" alt=""/></a>
  <a href="dic/f"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/f.png" height="20" width="20" alt=""/></a>
  <a href="dic/g"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/g.png" height="20" width="20" alt=""/></a>
  <a href="dic/h"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/h.png" height="20" width="20" alt=""/></a>
  <a href="dic/i"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/i.png" height="20" width="20" alt=""/></a>
  <a href="dic/j"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/j.png" height="20" width="20" alt=""/></a>
  <a href="dic/k"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/k.png" height="20" width="20" alt=""/></a>
  <a href="dic/l"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/l.png" height="20" width="20" alt=""/></a>
  <a href="dic/m"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/m.png" height="20" width="20" alt=""/></a>
  <a href="dic/n"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/n.png" height="20" width="20" alt=""/></a>
  <a href="dic/o"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/o.png" height="20" width="20" alt=""/></a>
  <a href="dic/p"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/p.png" height="20" width="20" alt=""/></a>
  <a href="dic/q"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/q.png" height="20" width="20" alt=""/></a>
  <a href="dic/r"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/r.png" height="20" width="20" alt=""/></a>
  <a href="dic/s"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/s.png" height="20" width="20" alt=""/></a>
  <a href="dic/t"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/t.png" height="20" width="20" alt=""/></a>
  <a href="dic/u"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/u.png" height="20" width="20" alt=""/></a>
  <a href="dic/v"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/v.png" height="20" width="20" alt=""/></a>
  <a href="dic/w"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/w.png" height="20" width="20" alt=""/></a>
  <a href="dic/x"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/x.png" height="20" width="20" alt=""/></a>
  <a href="dic/y"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/y.png" height="20" width="20" alt=""/></a>
  <a href="dic/z"><img style='float:left;clear:none;margin:10px;' class="img-responsive" src="img/letras/z.png" height="20" width="20" alt=""/></a>


</div>
<br>
<br>
<div style="margin: 0px auto; text-align: center; width: 1900px;">

  <img class="img-responsive" src="img/letras/d.png" height="72" width="72" alt="" style="center">
  <hr>
  <div class="col-lg-6 col-lg-offset-3 well">
    <hr>
    <table class="paperlist" style="text-align: justify">
      <tbody>
      <tr>
        <td >
          <strong>Daltonismo</strong>  defecto genético que ocasiona dificultad para distinguir los colores.
          La palabra daltonismo proviene del químico y matemático John Dalton que padecía este trastorno. El grado
          de afectación es muy variable y oscila entre la falta de capacidad para discernir cualquier color
          (acromatopsia) y un ligero grado de dificultad para distinguir algunos matices de rojo, verde y
          ocasionalmente azul . A pesar de que la sociedad en general considera que el daltonismo pasa inadvertido
          en la vida diaria, supone un problema para los afectados en ámbitos tan diversos como: valorar el estado
          de frescura de determinados alimentos, identificar códigos de colores de planos o elegir determinadas
          profesiones para las que es preciso superar un reconocimiento médico que implica identificar correctamente
          los colores (militar de carrera, piloto, capitán de marina mercante, policía, etc.).
          Puede detectarse mediante test visuales específicos como las cartas de Ishihara.
        </td>
      </tr>

      <tr>
        <td >
          <strong>Decusación</strong>  término utilizado en contextos biológicos para describir un cruce. En términos anatómicos en latín
          se usa la forma decussatio, por ejemplo en decussatio pyramidum. En anatomía el término quiasma significa
          casi lo mismo que decusación.
        </td>
      </tr>

      <tr>
        <td >
          <strong>Delirio</strong> En psiquiatría y psicología, el delirio (del latín de-lirare, "salir del surco al labrar la tierra") es un síntoma propio de las psicosis.
        </td>
      </tr>

      <tr>
        <td >
          <strong>Delírium trémens</strong> Se denomina delirium tremens (o delírium trémens, según el Diccionario panhispánico de dudas de la RAE) —locución en latín que significa
          "delirio tembloroso"— al síndrome de abstinencia del alcohol; propiamente se trata de la tercera fase,
          la más aguda de este síndrome. Al parecer, también puede darse como complicación en una intoxicación por
          benzodiacepinas o barbitúricos. Delirium Tremens (DT) fue descrito por primera vez en 1813, es un episodio
          agudo de delirio causado frecuentemente por el síndrome de abstinencia del alcohol. Las benzodiacepinas se
          usan como tratamiento palitivo para evitarse el DT cuando se interna al individuo alcohólico en centros de
          rehabilitación.
        </td>
      </tr>

      <tr>
        <td >
          <strong>Demencia</strong> (del latín de: "alejado" + mens (genitivo mentis): "mente") es la pérdida progresiva de las funciones
          cognitivas debida a daños o desórdenes cerebrales. Característicamente, esta alteración cognitiva provoca
          incapacidad para la realización de las actividades de la vida diaria. En el año 2014 se calculó un total de
          47.5 millones de casos registrados en el mundo, cuyo impacto en las personas enfermas y sus familias
          representa un gran problema de salud.
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

      <tr>
        <td >
          <strong></strong>
        </td>
      </tr>

    </table>
    <div>
      <a class="izquierda" href="dic/c"><i class="fa fa-arrow-left fa-3x"></i></a>
      <a class="derecha" href="dic/e"><i class="fa fa-arrow-right fa-3x"></i></a>
    </div>
    <br>
    <br>
    <br>
    <p style="text-align: justify"><i class="fa fa-pencil-square-o"></i> Si quieres colaborar en esta sección, puedes ponerte en contacto con nosotros utilizando este <a href="mailto:contacto@lawebdeneurociencia.com">formulario</a>.</p>
  </div>
</div>

</html>

app/views/dic/g.html.erb
<html lang="es">
<nav>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</nav>
<br>
<br>
<body>
<div style="margin: 0px auto; text-align: center; width: 1150px;" >

  <a href="dic/diccionario"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/a.png" height="20" width="20" alt=""/></a>
  <a href="dic/b"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/b.png" height="20" width="20" alt=""/></a>
  <a href="dic/c"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/c.png" height="20" width="20" alt=""/></a>
  <a href="dic/d"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/d.png" height="20" width="20" alt=""/></a>
  <a href="dic/e"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/e.png" height="20" width="20" alt=""/></a>
  <a href="dic/f"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/f.png" height="20" width="20" alt=""/></a>
  <a href="dic/g"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/g.png" height="20" width="20" alt=""/></a>
  <a href="dic/h"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/h.png" height="20" width="20" alt=""/></a>
  <a href="dic/i"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/i.png" height="20" width="20" alt=""/></a>
  <a href="dic/j"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/j.png" height="20" width="20" alt=""/></a>
  <a href="dic/k"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/k.png" height="20" width="20" alt=""/></a>
  <a href="dic/l"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/l.png" height="20" width="20" alt=""/></a>
  <a href="dic/m"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/m.png" height="20" width="20" alt=""/></a>
  <a href="dic/n"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/n.png" height="20" width="20" alt=""/></a>
  <a href="dic/o"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/o.png" height="20" width="20" alt=""/></a>
  <a href="dic/p"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/p.png" height="20" width="20" alt=""/></a>
  <a href="dic/q"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/q.png" height="20" width="20" alt=""/></a>
  <a href="dic/r"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/r.png" height="20" width="20" alt=""/></a>
  <a href="dic/s"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/s.png" height="20" width="20" alt=""/></a>
  <a href="dic/t"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/t.png" height="20" width="20" alt=""/></a>
  <a href="dic/u"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/u.png" height="20" width="20" alt=""/></a>
  <a href="dic/v"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/v.png" height="20" width="20" alt=""/></a>
  <a href="dic/w"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/w.png" height="20" width="20" alt=""/></a>
  <a href="dic/x"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/x.png" height="20" width="20" alt=""/></a>
  <a href="dic/y"><img style='float:left;clear:none;margin:12px;' class="img-responsive" src="img/letras/y.png" height="20" width="20" alt=""/></a>
  <a href="dic/z"><img style='float:left;clear:none;margin:10px;' class="img-responsive" src="img/letras/z.png" height="20" width="20" alt=""/></a>


</div>
<br>
<br>
<div style="margin: 0px auto; text-align: center; width: 1900px;">

  <img class="img-responsive" src="img/letras/g.png" height="72" width="72" alt="" style="center">
  <hr>
  <div class="col-lg-6 col-lg-offset-3 well">
    <hr>

    <div>
      <a class="izquierda" href="dic/f"><i class="fa fa-arrow-left fa-3x"></i></a>
      <a class="derecha" href="dic/h"><i class="fa fa-arrow-right fa-3x"></i></a>
    </div>
    <br>
    <br>
    <br>
    <p style="text-align: justify"><i class="fa fa-pencil-square-o"></i> Si quieres colaborar en esta sección, puedes ponerte en contacto con nosotros utilizando este <a href="mailto:contacto@lawebdeneurociencia.com">formulario</a>.</p>
  </div>
</div>

</html>

app/views/docs/atencion.html.erb
<html lang="es">
<nav>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</nav>
<br>
<br>

<div class="col-lg-6 col-lg-offset-3 well">
  <h3><b>Atención</b></h3>

  <p style="text-align: justify">
    La atención es la capacidad que tiene alguien para entender las cosas o un objetivo, tenerlo en cuenta o en
    consideración. Desde el punto de vista de la psicología, la atención no es un concepto único, sino el nombre
    atribuido a una variedad de fenómenos. Tradicionalmente, se ha considerado de dos maneras distintas, aunque
    relacionadas. Por una parte, la atención como una cualidad de la percepción hace referencia a la función de la
    atención como filtro de los estímulos ambientales, decidiendo cuáles son los estímulos más relevantes y dándoles
    prioridad por medio de la concentración de la actividad psíquica sobre el objetivo, para un procesamiento más
    profundo en la conciencia. Por otro lado, la atención es entendida como el mecanismo que controla y regula los
    procesos cognitivos; desde el aprendizaje por condicionamiento hasta el razonamiento complejo.

  </p>

  <p style="text-align: justify">
    En muchos casos actúa de manera inconsciente iniciado en el hemisferio cerebral izquierdo y es mantenida en el
    hemisferio derecho. El estar atento ("Poner atención" o "prestar atención") tampoco es un comportamiento único del
    ser humano.
  </p>

  <p style="text-align: justify">
    Hay estudios del Massachusetts Institute of Technology donde varios científicos y estudiantes comprueban que tanto se
    puede afectar la atención de un individuo. Uno de los principales objetivos era ver si una persona era capaz de
    mantener la atención, teniendo en el oído un auricular al estar entablando un conversación o escuchando a otra
    persona. Como ya se había dicho anteriormente "prestar atención" no es un comportamiento único del ser humano.
    algunos experimentos fracasaron, pero la mayoría lograron entender lo que se les estaba diciendo o ya sea mantener
    la conversación. Esto depende a que altura de sonido se este escuchando o también de que tipo de melodía se esta
    escuchando, ya que las de carácter un poco ruidosas como el rock es mas difícil que una persona logre entender la
    información que se le de.


  </p>

  <p style="text-align: justify">

  </p>

  <p style="text-align: justify">

  </p>

  <p style="text-align: justify">

  </p>

  <p style="text-align: justify">

  </p>

  <h2 style="text-align: right; font-size: 12px;">Fuente:<a
  href="https://en.wikipedia.org/wiki/Portal:Neuroscience" title="Wikipedia" target="new"> <i
  class="fa fa-wikipedia-w"></i></a></h2>

  <br>
</div>

app/views/papers/edit.html.erb
<br>
<br>
<div class="col-lg-6 col-lg-offset-2" well>
<h2>Editar el documento</h2>
</div>
<br>
<br>
<br>
<%= render 'form' %>

<div class="col-lg-6 col-lg-offset-3">
<%= link_to 'Mostrar', @paper %>  |
<%= link_to 'Atras', papers_path %>
</div>

app/views/papers/index.html.erb
<br>
<br>

<p id="notice"><%= notice %></p>
<hr>
<h2 class="text-center">Listado de Documentos</h2>
<hr>
<table class="paperlist" style="margin: 0px auto; text-align: left; width: 1000px;">
  <thead>
    <tr>
      <th>Id</th>
      <th>Autores</th>
      <th>Título</th>
      <th>Año</th>
      <th>Idioma</th>
      <th>Descarga</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.id %></td>
        <td><%= paper.autores %></td>
        <td><%= paper.título %></td>
        <td><%= paper.año %></td>
        <td><%= paper.idioma %></td>
        <td><a href="<%= paper.descarga %>"><%= paper.descarga %></a></td>
        <td><%= link_to 'Mostrar', paper %></td>
     <!--   <td><%= link_to 'Editar', edit_paper_path(paper) %></td>
        <td><%= link_to 'Borrar', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<!-- <%= link_to 'Crear Documento Nuevo', new_paper_path %> -->
  <br>
  <hr>
</div>

app/views/papers/new.html.erb
<br>
<br>
<div class="col-lg-6 col-lg-offset-2" well>
  <h2>Crear nuevo documento</h2>
</div>
   <%= render 'form' %>

   <%= link_to 'Atras', papers_path %>
</div>

<hr>

app/views/papers/show.html.erb
<html lang="es">
<br>
<br>
<nav>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</nav>
<br>
<br>
<div class="col-lg-6 col-lg-offset-3 well">
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @paper.id %>
</p>

<p>
  <strong>Autores:</strong>
  <%= @paper.autores %>
</p>

<p>
  <strong>Título:</strong>
  <%= @paper.título %>
</p>

<p>
  <strong>Año:</strong>
  <%= @paper.año %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @paper.idioma %>
</p>

<p>
  <strong>Descarga:</strong>
  <a href="<%= @paper.descarga %>"><%= @paper.descarga %></a>
</p>

<!-- <%= link_to 'Editar', edit_paper_path(@paper) %> | -->
<%= link_to 'Atrás', papers_path %>
</div>

<br>
<br>